spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/real_estate
  
  datasource:
    url: jdbc:mysql://localhost:3306/real_estate
    username: root
    password: 1234
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
server:
  port: ${SERVER_PORT:8089}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher